-- Financing quotes generated by the Quoter. Each quote optionally links to a
-- lead (lead_id nullable — one-off quotes keep only a free-text client_name).
-- The financial figures are SNAPSHOTTED on the row (not derived from the FKs):
-- unit prices and terms change over time, so "what was quoted, and when" must
-- reflect the numbers as they were at quote time.
-- Readable/insertable/updatable by all authenticated users; deletes by admins.
create table public.quotes (
  id             uuid primary key default gen_random_uuid(),
  lead_id        uuid references public.leads (id) on delete set null,
  project_id     uuid references public.projects (id) on delete set null,
  unit_id        uuid references public.inventory (id) on delete set null,
  client_name    text,
  currency       text,
  price          numeric,
  down_pct       numeric,
  down_amount    numeric,
  financed       numeric,
  term_years     int,
  term_months    int,
  interest_rate  numeric,
  monthly_payment numeric,
  total          numeric,
  sent           boolean not null default false,
  sent_at        timestamptz,
  advisor_id     uuid references public.profiles (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index quotes_lead_id_idx    on public.quotes (lead_id);
create index quotes_project_id_idx on public.quotes (project_id);
create index quotes_advisor_id_idx on public.quotes (advisor_id);
create index quotes_created_at_idx on public.quotes (created_at);

-- Keep updated_at current on every row update (reuses public.set_updated_at()).
create trigger quotes_set_updated_at
  before update on public.quotes
  for each row execute function public.set_updated_at();

alter table public.quotes enable row level security;

-- Read: any authenticated user (admin + executive).
create policy "quotes_read_authenticated" on public.quotes
  for select to authenticated using (true);

-- Insert: any authenticated user (advisors record their own quotes).
create policy "quotes_insert_authenticated" on public.quotes
  for insert to authenticated with check (true);

-- Update: any authenticated user (e.g. toggling the sent flag).
create policy "quotes_update_authenticated" on public.quotes
  for update to authenticated using (true) with check (true);

-- Delete: admins only.
create policy "quotes_delete_admin" on public.quotes
  for delete to authenticated using (public.is_admin());
